### ISSUE TITLE
Add positions to board 3D model

### ISSUE THREAD

**Issue by timkoeppel** [timkoeppel/vr-browser-chess#18]
Add Positions to the board 3D model so the player knows the position names

**Comment by timkoeppel** [comment]
![Screenshot 2021-11-18 232454](https://user-images.githubusercontent.com/69720379/142506561-a49a8d2b-db55-41eb-b118-53188f0abd25.png)

**Comment by efebozkir** [comment]
Nice looking letters and numbers!
